"""
Django settings for cognix project.

This file contains the configuration for the Cognix project.
It is structured to be production-ready with clear separation of concerns.
Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see:
    https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see:
    https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# =============================================================================
# Base Configuration
# =============================================================================

import os
from pathlib import Path
import dj_database_url

# Environment variables management
# Loads .env file for local development. In production, environment variables
# should be set directly on the server or container.
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# This ensures that file paths are constructed correctly regardless of the
# operating system.
BASE_DIR = Path(__file__).resolve().parent.parent

# =============================================================================
# Security Settings
# =============================================================================

# SECURITY WARNING: Keep the secret key used in production secret!
# This key is used for cryptographic signing. Never commit it to version control.
# In production, always set this via environment variable.
SECRET_KEY = os.getenv("SECRET_KEY", "unsafe-secret-key")

# SECURITY WARNING: Don't run with debug turned on in production!
# DEBUG mode exposes sensitive information and should only be used during development.
# Set DEBUG=False in production for security and performance.
DEBUG = os.getenv("DEBUG", "False") == "True"

# Hosts/domains that this Django site can serve.
# In production, set ALLOWED_HOSTS to your domain(s) as a comma-separated string.
# Example: "example.com,www.example.com"
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# Controls how WhiteNoise finds static files.
# When DEBUG=False, WhiteNoise uses its integrated finders for better performance.
WHITENOISE_USE_FINDERS = DEBUG

# Enforce HTTPS redirect when not in debug mode.
# SECURITY: Redirects all HTTP traffic to HTTPS in production.
SECURE_SSL_REDIRECT = False if DEBUG else True

# Login URL for authentication redirects.
LOGIN_URL = 'login'

# Security headers and protections
# SECURE_BROWSER_XSS_FILTER: Enables the browser's XSS filtering.
SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF: Prevents the browser from MIME-sniffing a response.
SECURE_CONTENT_TYPE_NOSNIFF = True
# X_FRAME_OPTIONS: Prevents clickjacking by denying framing.
X_FRAME_OPTIONS = 'DENY'

# Cookie security settings
# Set secure flags for CSRF and session cookies when not in debug mode.
# In production (DEBUG=False), cookies will only be sent over HTTPS.
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG

# Header that Django uses to detect HTTPS when behind a proxy.
# Required when the application is behind a reverse proxy that terminates SSL.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# =============================================================================
# Application Definition
# =============================================================================

INSTALLED_APPS = [
    # Django core apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'social_django',          # Social authentication (Google OAuth2)
    'rest_framework',         # Django REST Framework for API endpoints
    'corsheaders',            # Cross-Origin Resource Sharing headers

    # Local apps
    'main',                   # Main application for the Cognix project
]

MIDDLEWARE = [
    # CORS middleware should be placed as high as possible to handle preflight requests.
    'corsheaders.middleware.CorsMiddleware',   # Handles CORS headers

    # Security and performance middleware
    'django.middleware.security.SecurityMiddleware',  # Security enhancements
    'whitenoise.middleware.WhiteNoiseMiddleware',    # Static file serving in production

    # Core Django middleware
    'django.contrib.sessions.middleware.SessionMiddleware',  # Manages sessions
    'django.middleware.common.CommonMiddleware',             # URL rewriting, etc.
    'django.middleware.csrf.CsrfViewMiddleware',             # CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Associates users with requests
    'django.contrib.messages.middleware.MessageMiddleware',   # Manages temporary messages
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # Clickjacking protection
]

# Root URL configuration module.
ROOT_URLCONF = 'cognix.urls'

# =============================================================================
# Templates Configuration
# =============================================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # List of additional template directories (empty by default)
        'APP_DIRS': True,  # Look for templates in app directories (e.g., main/templates)
        'OPTIONS': {
            'context_processors': [

                'django.template.context_processors.debug',     # Adds debug info
                'django.template.context_processors.request',   # Adds the request object
                'django.contrib.auth.context_processors.auth',  # Adds user object
                'django.contrib.messages.context_processors.messages',  # Adds messages
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

# WSGI application entry point.
WSGI_APPLICATION = 'cognix.wsgi.application'

# =============================================================================
# Database Configuration
# =============================================================================

# Database configuration using dj-database-url.
# This supports multiple database backends via DATABASE_URL environment variable.
# Defaults to SQLite for local development if DATABASE_URL is not set.
# conn_max_age=600 enables persistent database connections for better performance.
DATABASES = {
    'default': dj_database_url.parse(
        os.getenv("DATABASE_URL", "sqlite:///db.sqlite3"),
        conn_max_age=600
    )
}

# =============================================================================
# Authentication & Password Validation
# =============================================================================

# Authentication backends for user login.
# Supports both Google OAuth2 (via social-auth-app-django) and standard Django auth.
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',  # Google OAuth2 authentication
    'django.contrib.auth.backends.ModelBackend', # Standard Django authentication
)

# Redirect URLs after login and logout.
LOGIN_REDIRECT_URL = '/'   # Redirect to homepage after login
LOGOUT_REDIRECT_URL = '/'  # Redirect to homepage after logout

# Password validators to enforce strong passwords.
# These validators are run during password changes and user creation.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        # Prevents passwords that are too similar to user attributes.
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        # Enforces a minimum password length (default is 8).
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        # Prevents the use of commonly used passwords.
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        # Prevents passwords that are entirely numeric.
    },
]

# Google OAuth2 credentials for social authentication.
# These must be set in environment variables for security.
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv("SOCIAL_AUTH_GOOGLE_OAUTH2_KEY")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv("SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET")

# =============================================================================
# Internationalization & Localization
# =============================================================================

# Language code for this installation.
LANGUAGE_CODE = 'en-us'

# Time zone for date/time display and storage.
# 'UTC' is recommended for consistency across servers.
TIME_ZONE = 'UTC'

# Enable internationalization (i18n) support.
USE_I18N = True

# Enable timezone-aware datetime handling.
USE_TZ = True

# =============================================================================
# Static & Media Files
# =============================================================================

# URL that serves static files.
STATIC_URL = '/static/'

# Directories where Django looks for static files (in addition to app static directories).
STATICFILES_DIRS = [
    BASE_DIR / "main/static",  # Static files specific to the 'main' app
]

# Destination directory for collected static files.
# This is used by the 'collectstatic' management command.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Storage backend for static files in production.
# WhiteNoise's CompressedManifestStaticFilesStorage compresses files and adds
# a content-based hash to filenames for cache busting.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# =============================================================================
# CORS & API Settings
# =============================================================================

# CORS (Cross-Origin Resource Sharing) configuration.
# Allows or restricts frontend applications from accessing the API.

# Disallow all origins by default. Only explicitly allowed origins can access the API.
CORS_ALLOW_ALL_ORIGINS = False

# List of origins that are allowed to make cross-origin requests.
# In development, you might include http://localhost:3000 for React/Vue frontends.
# In production, add your frontend domain(s).
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",   # Local development frontend
    # "https://your-frontend-domain.com",  # Uncomment and add your production frontend
]

# Django REST Framework configuration.
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Require authentication by default
    ],
    # Additional DRF settings can be added here as needed:
    # 'DEFAULT_AUTHENTICATION_CLASSES': [...],
    # 'DEFAULT_PAGINATION_CLASS': ...,
}

# =============================================================================
# Other Configurations
# =============================================================================

# Default primary key field type.
# 'django.db.models.BigAutoField' is recommended for new projects as it uses
# 64-bit integers, reducing the risk of ID exhaustion.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# Notes for Production Deployment
# =============================================================================
# - Ensure that SECRET_KEY, DATABASE_URL, and social auth keys are set as
#   environment variables and never hardcoded.
# - Set DEBUG=False in production.
# - Update ALLOWED_HOSTS with your actual domain name(s).
# - For HTTPS, ensure your web server (nginx, Apache) handles SSL termination
#   and sets the X-Forwarded-Proto header appropriately.
# - Review CORS_ALLOWED_ORIGINS and add your frontend domain(s) in production.
# - For performance, consider using a dedicated static file server or CDN.